### ISSUE TITLE
Does not work under Node.js v6 on Alpine Linux

### ISSUE THREAD

**Issue by sonicdoe** [SonicHedgehog/detect-character-encoding#11]
```
Error: Error relocating /usr/src/app/build/Release/icuWrapper.node: utrace_cleanup_59: symbol not found
```

Originally reported in https://github.com/sonicdoe/detect-character-encoding/issues/8#issuecomment-326189423.

**Comment by willfarrell** [comment]
I just ran into this using `node:8-alpine`, but getting a slightly different error. I posted it below just in case it's helpful.

```
/var/www/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error relocating /var/www/node_modules/detect-character-encoding/build/Release/icuWrapper.node: ucnv_open_61: symbol not found
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at bindings (/var/www/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/www/node_modules/detect-character-encoding/index.js:3:37)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by sonicdoe** [comment]
I’ve actually dropped support for Alpine Linux a while ago (see https://github.com/sonicdoe/detect-character-encoding/commit/5cbba15278428766833dd97c92cdf7f1bead38c1). Sorry for keeping this (now misleading) issue open.

I’d really like to support Alpine Linux, however, it has proven to be quite difficult in the past. If you don’t actually need ICU itself, I’d strongly suggest taking a look at [ced](https://github.com/sonicdoe/ced).
