### ISSUE TITLE
Could not install detect-character-encoding

### ISSUE THREAD

**Issue by diogodomanski** [SonicHedgehog/detect-character-encoding#25]
I've added detect-character-encoding to my project, but I'm not being able to compile it. I get the following error message:

```bash
error /home/domanski/Projects/visitown-api/node_modules/detect-character-encoding: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/domanski/Projects/visitown-api/node_modules/detect-character-encoding
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@12.18.2 | linux | x64
gyp info find Python using Python version 3.8.6 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/domanski/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/domanski/Projects/visitown-api/node_modules/detect-character-encoding/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/domanski/Projects/visitown-api/node_modules/detect-character-encoding/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/domanski/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/domanski/.cache/node-gyp/12.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/domanski/.cache/node-gyp/12.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/domanski/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/domanski/.cache/node-gyp/12.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/domanski/Projects/visitown-api/node_modules/detect-character-encoding',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/domanski/Projects/visitown-api/node_modules/detect-character-encoding/build'
  TOUCH Release/obj.target/vendor/icu/icu_implementation.stamp
  TOUCH Release/obj.target/vendor/icu/icu_uconfig.stamp
  TOUCH Release/obj.target/vendor/icu/icu_uconfig_target.stamp
  CXX(target) Release/obj.target/icui18n/vendor/icu/i18n/ucsdet.o
make: g++: No such file or directory
make: *** [vendor/icu/icui18n.target.mk:142: Release/obj.target/icui18n/vendor/icu/i18n/ucsdet.o] Error 127
make: Leaving directory '/home/domanski/Projects/visitown-api/node_modules/detect-character-encoding/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/domanski/.config/yarn/global/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.8.0-33-generic
gyp ERR! command "/usr/bin/node" "/home/domanski/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/domanski/Projects/visitown-api/node_modules/detect-character-encoding
```
My environment is:
UBUNTU 20.10
Node: 12.19
NPM: 6.14.8
Yarn: 1.22.5

I guess that it has something to do with ICU, but I don't know what to do to set it up of fix it. I've just bought a new laptop and it is a fresh new ubuntu installation. In my previous laptop (with same Ubuntu version) my project used to compile with no problems.

Can anyone help me?

**Comment by diogodomanski** [comment]
Problem solved: It only required g++ installation. (sudo apt install g++)

**Comment by sonicdoe** [comment]
I’m glad you resolved it. Since detect-character-encoding is a C++ addon, it indeed requires various build tools. [I’ve now documented that in the readme](https://github.com/sonicdoe/detect-character-encoding/commit/fb9c633bbf26ea1b14799293bd2895d5d002b4b8). On Ubuntu, `sudo apt install build-essential` is probably the easiest way.

**Comment by diogodomanski** [comment]
@sonicdoe Exactly. build-essential package is the easiest way... Thanks for ready reply and congratulations for the greate job.
