### ISSUE TITLE
The install script fails

### ISSUE THREAD

**Issue by kulicuu** [SonicHedgehog/detect-character-encoding#7]
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/admin/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at emitOne (events.js:120:20)
gyp ERR! stack     at Request.emit (events.js:210:7)
gyp ERR! stack     at Request.onRequestResponse (/home/admin/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/request/request.js:1074:10)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/home/admin/.nvm/versions/node/v8.1.1/bin/node" "/home/admin/.nvm/versions/node/v8.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin/pg5/node_modules/detect-character-encoding
gyp ERR! node -v v8.1.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN @0.0.5-alpha No description
npm WARN @0.0.5-alpha No repository field.
npm WARN @0.0.5-alpha No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detect-character-encoding@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the detect-character-encoding@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2017-06-14T08_54_22_338Z-debug.log


```

**Comment by sonicdoe** [comment]
This is related to https://github.com/nodejs/node-gyp/issues/1230. According to https://github.com/nodejs/node/issues/13672#issuecomment-308347430, Node.js will “be pushing a new version ASAP to resolve this”.

**Comment by sonicdoe** [comment]
This problem should now be solved, see https://github.com/nodejs/node/issues/13667#issuecomment-308710990.
